# Site settings
title: 3Dots IT Solutions
description: A startup company to build smart systems
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 3Dots
user_description: A startup company to build smart systems
user_title: IT system Solutions
email: eng.amaralaa@gmail.com
twitter_username: SOON
github_username:  3dotsIT
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']